"use client";
import { useState } from "react";

const items=[
  {icon:"✧",title:"Chat",sub:"Ask NEXA anything",tab:"assistant"},
  {icon:"✓",title:"Tasks",sub:"Organize your to-do list",tab:"tasks"},
  {icon:"▣",title:"Calendar",sub:"Plan your schedule",tab:"calendar"},
  {icon:"•••",title:"More",sub:"Goals, notes & settings",tab:"profile"}
];
const tasks=[
  ["Finish website design","09:00 AM","done"],["Study HTML & CSS","11:00 AM","blue"],["Buy groceries","04:00 PM","yellow"],["Call Mom","06:00 PM","pink"],["Workout","07:30 PM","purple"]
];
function Orb({small=false}:{small?:boolean}){return <div className={"orb "+(small?"orbSmall":"")}><span>N</span></div>}
function Icon({children}:{children:React.ReactNode}){return <div className="iconBox">{children}</div>}
function Bottom({tab,setTab}:{tab:string,setTab:(x:string)=>void}){return <nav className="bottom"><button onClick={()=>setTab("home")} className={tab==="home"?"active":""}>⌂<small>Home</small></button><button onClick={()=>setTab("tasks")} className={tab==="tasks"?"active":""}>✓<small>Tasks</small></button><button onClick={()=>setTab("assistant")} className="orbNav"><Orb small/></button><button onClick={()=>setTab("calendar")} className={tab==="calendar"?"active":""}>▣<small>Calendar</small></button><button onClick={()=>setTab("profile")} className={tab==="profile"?"active":""}>♙<small>Profile</small></button></nav>}
function Home({setTab}:{setTab:(x:string)=>void}){return <><header className="top"><span className="brand">NEXA</span><div className="avatar">S</div></header><section><p className="eyebrow">Good Morning,</p><h1>Sam <b>♛</b></h1><p className="muted">Here's what's happening today.</p></section><div className="heroCard"><div className="spark">✦</div><div><strong>You're on track!</strong><span>3 tasks completed today</span></div><b>›</b></div><div className="quickGrid">{items.map(x=><button key={x.tab} onClick={()=>setTab(x.tab)}><Icon>{x.icon}</Icon><span>{x.title}</span></button>)}</div><div className="sectionHead"><h2>Today's Schedule</h2><button>View all</button></div><div className="schedule">{[["Study / Work Session","09:00 AM - 11:00 AM","done"],["Lunch Break","12:00 PM - 01:00 PM",""],["Attend Online Class","03:00 PM - 05:00 PM",""]].map(([a,b,c])=><div className="scheduleRow" key={a}><i className={c}></i><div><strong>{a}</strong><small>{b}</small></div><span>{c?"✓":"○"}</span></div>)}</div></>}
function Assistant(){const [text,setText]=useState("");const [messages,setMessages]=useState<string[]>([]);return <><header className="assistantHead"><button>‹</button><div><strong>NEXA Assistant</strong><small><i/> Online</small></div><button>⚙</button></header><div className="assistantBody"><Orb/><h2>Hi Sam! 👋</h2><p>I'm NEXA, your personal assistant.<br/>How can I help you today?</p>{items.map(x=><button className="prompt" key={x.title} onClick={()=>setMessages(m=>[...m,x.title])}><Icon>{x.icon}</Icon><div><strong>{x.title==="Chat"?"Answer a question":x.title==="Tasks"?"Help with my tasks":x.title==="Calendar"?"Plan my day":"Set a reminder"}</strong><small>{x.sub}</small></div></button>)}{messages.map((m,i)=><div className="userMsg" key={i}>{m}</div>)}</div><div className="composer"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type your message..." onKeyDown={e=>{if(e.key==="Enter"&&text){setMessages(m=>[...m,text]);setText("")}}}/><button onClick={()=>{if(text){setMessages(m=>[...m,text]);setText("")}}}>➤</button></div></>}
function Tasks(){return <><header className="pageHead"><div><h2>Tasks</h2><p>Get things done, one step at a time.</p></div><button className="plus">+</button></header><div className="pills"><button className="selected">Today</button><button>Upcoming</button><button>Completed</button></div><div className="taskList">{tasks.map(([a,b,c])=><div className="task" key={a}><i className={c}>{c==="done"?"✓":""}</i><div><strong>{a}</strong><small>{b}</small></div></div>)}</div></>}
function Calendar(){return <><header className="pageHead"><div><h2>Calendar</h2><p>Your time, your power.</p></div></header><div className="calendar"><div className="calTitle"><button>‹</button><strong>July 2026</strong><button>›</button></div><div className="week">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><span key={x}>{x}</span>)}</div><div className="days">{Array.from({length:31},(_,i)=><button className={i===19?"today":""} key={i}>{i+1}</button>)}</div></div><h3 className="dateTitle">Today, July 20</h3><div className="agenda">{[["Study / Work Session","09:00 AM - 11:00 AM","blue"],["Lunch Break","12:00 PM - 01:00 PM","purple"],["Attend Online Class","03:00 PM - 05:00 PM","green"],["Gym","07:00 PM - 08:30 PM","pink"]].map(x=><div key={x[0]}><i className={x[2]}/><span><strong>{x[0]}</strong><small>{x[1]}</small></span></div>)}</div></>}
function Profile({setTab}:{setTab:(x:string)=>void}){return <><div className="profileTop"><div className="bigAvatar">S</div><div><h2>Sam</h2><small>sam@gmail.com</small></div></div><button className="premiumRow" onClick={()=>setTab("premium")}><span>♛</span><div><strong>NEXA Premium</strong><small>Unlock more features</small></div>›</button><div className="settings">{[["✦","My Goals","Set and track your goals"],["♧","Notifications","Manage your alerts"],["◉","Appearance","Choose your theme"],["◎","Language","English"],["?","Help & Support","Get help when you need it"],["ⓘ","About NEXA","Version 1.0.0"]].map(x=><button key={x[1]}><Icon>{x[0]}</Icon><div><strong>{x[1]}</strong><small>{x[2]}</small></div><span>›</span></button>)}</div></>}
function Premium({setTab}:{setTab:(x:string)=>void}){return <div className="premium"><div className="mountains"/><span className="premiumBrand">N E X A</span><b>♛ Premium</b><h1>Unlock Your<br/>Full Potential</h1><p>Get more features, more control,<br/>and a smarter experience.</p><ul>{["Unlimited tasks & reminders","Advanced AI assistant","Custom themes","Priority support","Ad-free experience"].map(x=><li key={x}>✓ {x}</li>)}</ul><button className="cta">Upgrade to Premium</button><button className="later" onClick={()=>setTab("profile")}>Maybe Later</button></div>}
export default function Page(){const [intro,setIntro]=useState(true);const [tab,setTab]=useState("home");if(intro)return <main className="stage"><div className="phone splash"><div className="status">9:41 <span>▮▮▮ ◼</span></div><div className="splashGlow"/><Orb/><div className="logoText">N E X A</div><p>Your Personal Assistant<br/>for a Smarter Life</p><div className="loader"/><small>Organize&nbsp; · &nbsp;Plan&nbsp; · &nbsp;Achieve</small><button className="tap" onClick={()=>setIntro(false)}>Get Started&nbsp; →</button></div><div className="phone onboarding"><div className="status">9:41 <span>▮▮▮ ◼</span></div><span className="brand">NEXA</span><h1>More than<br/>just an <b>assistant.</b></h1><p>NEXA helps you stay organized,<br/>boost your productivity and<br/>handle everyday tasks — effortlessly.</p><div className="deviceArt"><Orb/><span>▣</span><span>✉</span><span>▣</span></div><button className="cta" onClick={()=>setIntro(false)}>Get Started&nbsp; →</button><small>Already have an account? <u>Log In</u></small></div></main>;return <main className="app"><div className="phone"><div className="status">9:41 <span>▮▮▮ ◼</span></div>{tab==="home"&&<Home setTab={setTab}/>} {tab==="assistant"&&<Assistant/>}{tab==="tasks"&&<Tasks/>}{tab==="calendar"&&<Calendar/>}{tab==="profile"&&<Profile setTab={setTab}/>} {tab==="premium"&&<Premium setTab={setTab}/>} {tab!=="assistant"&&<Bottom tab={tab} setTab={setTab}/>}</div></main>}