import fs from 'node:fs';
import path from 'node:path';

const manifest=path.join(process.cwd(),'android/app/src/main/AndroidManifest.xml');
if(!fs.existsSync(manifest)) throw new Error('AndroidManifest.xml was not generated by Capacitor.');
let xml=fs.readFileSync(manifest,'utf8');
const permissions=['android.permission.INTERNET','android.permission.RECORD_AUDIO','android.permission.POST_NOTIFICATIONS'];
for(const permission of permissions){if(!xml.includes(`android:name="${permission}"`)){xml=xml.replace('<manifest ',`<manifest `);xml=xml.replace(/(<manifest[^>]*>)/,`$1\n    <uses-permission android:name="${permission}" />`);}}
fs.writeFileSync(manifest,xml);

const gradle=path.join(process.cwd(),'android/app/build.gradle');
if(fs.existsSync(gradle)){
  let g=fs.readFileSync(gradle,'utf8');
  if(!g.includes('versionName')) g += '\n';
  fs.writeFileSync(gradle,g);
}
